### ISSUE TITLE
Conflict with Elementor, Page Links to, and Wordpress 5.1

### ISSUE THREAD

**Issue by normprosser** [markjaquith/page-links-to#66]
Hi there Mark,

I'm trying to use 'Page Links To' to link to external URL's instead of default post internal url's. It all works, however when I attempt to edit the post with Elementor it will only open in what they call 'Safe Mode.'

Do you know if this would be a conflict between Elementor and Page Links To, or conflict between Page Links To and Wordpress 5.1

Thanks....

Norm Prosser
norm@tips4success.com

**Comment by bourn404** [comment]
I'm running into the same issue.  I like to write an excerpt using Elementor to show up in my blog feed and then link to an external site.  Because of this issue I have to remove the link from the input box, uncheck the 'Custom Permalink' option box, and publish changes before I can use the Elementor editor.

**Comment by markjaquith** [comment]
Thanks for this report! What's happening is that Elementor is trying to load the post, which of course Page Links To is trying to redirect to the URL you specified. But I found a way to identify that Elementor is loading the post, and blocking the redirect in that specific case. This fix will be in the next release of the plugin.
