### ISSUE TITLE
Add rel=nofollow option

### ISSUE THREAD

**Issue by HughOMahony** [markjaquith/page-links-to#67]
It would be great if it were possible for this plugin to set the rel=nofollow attribute in addition to the option to open the target in a new tab. Is this possible for the next update?

**Comment by gcluley** [comment]
Seconding this request.  Adding rel="noopener" or rel="noreferrer" to target="_blank" links avoids some security issues.

https://web.dev/external-anchors-use-rel-noopener/

**Comment by markjaquith** [comment]
@gcluley Adding `rel="noopener"` is no problem — I can do that with JavaScript. I've opened issue #99 to track that. Thanks!

Adding `rel="noreferrer"` is tricker. Yes, I can also do that with JavaScript, but I'm not entirely sure if search engines will "honor" it. Because if they looked at the original source, there would be no `rel="noreferrer"`... it would get added on page load by JavaScript.

Unfortunately there is no universal way for me to add `rel="noreferrer"` to the HTML output of links... because these links can be generated by many different WordPress functions and not all of them let you also control the attributes being output. So any solution that sends `rel="noreferrer"` in the PHP-generated HTML would have to use PHP output buffering. Output buffering slows down your page, increases memory usage, and is susceptible to bugs and strange interactions with other code that uses output buffering (like many caching plugins, and SEO plugins).

So! I'm going to do some research, to see if adding `rel="noreferrer"` to links with JavaScript is something that Google will "accept" (i.e. by not passing PageRank and not penalizing advertising/advertorial links). If so, that's my ideal solution. If not, I can look into the output buffering solution.

But #99 can proceed regardless, as that is absolutely something that can be added by JS on the fly.

**Comment by gcluley** [comment]
Cheers Mark!

**Comment by marco-torretta** [comment]
@markjaquith what about rel=nofollow? 

Also, could it be possible to add checkboxes for rel=noopener and rel=nofollow when defining an external link in a post? This way one should have options to change external link rules individually.

**Comment by dvisan** [comment]
any plans to add rel="nofollow" in future version?

**Comment by markjaquith** [comment]
I'm working on an expansion plugin that'll handle additional features like this.
