### ISSUE TITLE
Conflict with Thrive Themes Architect

### ISSUE THREAD

**Issue by naguibihelek** [markjaquith/page-links-to#95]
Some of my Thrive Themes pages can no longer be accessed to edit using Thrive Architect due to conflict with "Page Links To" plugin.
Please advise what we need to do in order to resolve this.
Thrive Themes support have checked and verified issue is not with their plugins.

Thanks in advance.
Nagui

**Comment by markjaquith** [comment]
What is the error you are receiving?

**Comment by naguibihelek** [comment]
Mark,

I found the issue. Thanks for your prompt reply.
I was trying to edit a page, using “thrive themes architect", that is redirected by “page links to". I guess we can’t do that.

Is this something that should work?
It was a natural assumption, because we can open and edit the page using Wordpress native editor.

Best regards,

Nagui Bihelek
Founder and CEO
Cell phone: +1.403.616.4087
AccuMatch Behavior Intelligence

"Continue to be amazing, not in just who you are, in what you do.
No one can see who you are, but they sure see what you do.”

Schedule time with me:
http://accumatchbi.com/schedule-time-nagui/

websites: https://accumatchbi.com, https://naguibihelek.com

**Comment by markjaquith** [comment]
I'm not familiar with Thrive Themes Architect, but from a little reading, it seems like it's a front-end editing experience. That's not going to work with this plugin, because when you've pointed a piece of content to another URL, you can't "visit" that content on your site anymore without being redirected. So what's probably happening is that you're trying to edit it with Architect, which tries to open the piece of content, and Page Links To then redirects away.

If it's possible to choose, on a per-post basis, to use the WordPress native editor, I would recommend that, for any redirected posts.

**Comment by naguibihelek** [comment]
Ok. Thanks Mark.

Best regards,

Nagui Bihelek
Founder and CEO
Cell phone: +1.403.616.4087
AccuMatch Behavior Intelligence

"Continue to be amazing, not in just who you are, in what you do.
No one can see who you are, but they sure see what you do.”

Schedule time with me:
http://accumatchbi.com/schedule-time-nagui/

websites: https://accumatchbi.com, https://naguibihelek.com
